# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PopsiclesData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, price: str=None, menu_item: str=None, description: str=None):  # noqa: E501
        """PopsiclesData - a model defined in Swagger

        :param type: The type of this PopsiclesData.  # noqa: E501
        :type type: str
        :param price: The price of this PopsiclesData.  # noqa: E501
        :type price: str
        :param menu_item: The menu_item of this PopsiclesData.  # noqa: E501
        :type menu_item: str
        :param description: The description of this PopsiclesData.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'type': str,
            'price': str,
            'menu_item': str,
            'description': str
        }

        self.attribute_map = {
            'type': 'type',
            'price': 'price',
            'menu_item': 'menu_item',
            'description': 'description'
        }

        self._type = type
        self._price = price
        self._menu_item = menu_item
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'PopsiclesData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The popsicles-data of this PopsiclesData.  # noqa: E501
        :rtype: PopsiclesData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this PopsiclesData.


        :return: The type of this PopsiclesData.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this PopsiclesData.


        :param type: The type of this PopsiclesData.
        :type type: str
        """

        self._type = type

    @property
    def price(self) -> str:
        """Gets the price of this PopsiclesData.


        :return: The price of this PopsiclesData.
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price: str):
        """Sets the price of this PopsiclesData.


        :param price: The price of this PopsiclesData.
        :type price: str
        """

        self._price = price

    @property
    def menu_item(self) -> str:
        """Gets the menu_item of this PopsiclesData.


        :return: The menu_item of this PopsiclesData.
        :rtype: str
        """
        return self._menu_item

    @menu_item.setter
    def menu_item(self, menu_item: str):
        """Sets the menu_item of this PopsiclesData.


        :param menu_item: The menu_item of this PopsiclesData.
        :type menu_item: str
        """

        self._menu_item = menu_item

    @property
    def description(self) -> str:
        """Gets the description of this PopsiclesData.


        :return: The description of this PopsiclesData.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this PopsiclesData.


        :param description: The description of this PopsiclesData.
        :type description: str
        """

        self._description = description
