# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.purchase_schema_popsicles import PurchaseSchemaPopsicles  # noqa: F401,E501
from swagger_server import util


class PurchaseSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, payment_total: str=None, popsicles: List[PurchaseSchemaPopsicles]=None):  # noqa: E501
        """PurchaseSchema - a model defined in Swagger

        :param payment_total: The payment_total of this PurchaseSchema.  # noqa: E501
        :type payment_total: str
        :param popsicles: The popsicles of this PurchaseSchema.  # noqa: E501
        :type popsicles: List[PurchaseSchemaPopsicles]
        """
        self.swagger_types = {
            'payment_total': str,
            'popsicles': List[PurchaseSchemaPopsicles]
        }

        self.attribute_map = {
            'payment_total': 'payment_total',
            'popsicles': 'popsicles'
        }

        self._payment_total = payment_total
        self._popsicles = popsicles

    @classmethod
    def from_dict(cls, dikt) -> 'PurchaseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The purchase_schema of this PurchaseSchema.  # noqa: E501
        :rtype: PurchaseSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payment_total(self) -> str:
        """Gets the payment_total of this PurchaseSchema.


        :return: The payment_total of this PurchaseSchema.
        :rtype: str
        """
        return self._payment_total

    @payment_total.setter
    def payment_total(self, payment_total: str):
        """Sets the payment_total of this PurchaseSchema.


        :param payment_total: The payment_total of this PurchaseSchema.
        :type payment_total: str
        """

        self._payment_total = payment_total

    @property
    def popsicles(self) -> List[PurchaseSchemaPopsicles]:
        """Gets the popsicles of this PurchaseSchema.


        :return: The popsicles of this PurchaseSchema.
        :rtype: List[PurchaseSchemaPopsicles]
        """
        return self._popsicles

    @popsicles.setter
    def popsicles(self, popsicles: List[PurchaseSchemaPopsicles]):
        """Sets the popsicles of this PurchaseSchema.


        :param popsicles: The popsicles of this PurchaseSchema.
        :type popsicles: List[PurchaseSchemaPopsicles]
        """

        self._popsicles = popsicles
