# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PurchaseSchemaPopsicles(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, menu_item: str=None):  # noqa: E501
        """PurchaseSchemaPopsicles - a model defined in Swagger

        :param menu_item: The menu_item of this PurchaseSchemaPopsicles.  # noqa: E501
        :type menu_item: str
        """
        self.swagger_types = {
            'menu_item': str
        }

        self.attribute_map = {
            'menu_item': 'menu_item'
        }

        self._menu_item = menu_item

    @classmethod
    def from_dict(cls, dikt) -> 'PurchaseSchemaPopsicles':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The purchase_schema_popsicles of this PurchaseSchemaPopsicles.  # noqa: E501
        :rtype: PurchaseSchemaPopsicles
        """
        return util.deserialize_model(dikt, cls)

    @property
    def menu_item(self) -> str:
        """Gets the menu_item of this PurchaseSchemaPopsicles.


        :return: The menu_item of this PurchaseSchemaPopsicles.
        :rtype: str
        """
        return self._menu_item

    @menu_item.setter
    def menu_item(self, menu_item: str):
        """Sets the menu_item of this PurchaseSchemaPopsicles.


        :param menu_item: The menu_item of this PurchaseSchemaPopsicles.
        :type menu_item: str
        """

        self._menu_item = menu_item
