# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.popsicles_data import PopsiclesData  # noqa: F401,E501
from swagger_server import util


class StoreSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, menu: List[PopsiclesData]=None):  # noqa: E501
        """StoreSchema - a model defined in Swagger

        :param menu: The menu of this StoreSchema.  # noqa: E501
        :type menu: List[PopsiclesData]
        """
        self.swagger_types = {
            'menu': List[PopsiclesData]
        }

        self.attribute_map = {
            'menu': 'menu'
        }

        self._menu = menu

    @classmethod
    def from_dict(cls, dikt) -> 'StoreSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The store_schema of this StoreSchema.  # noqa: E501
        :rtype: StoreSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def menu(self) -> List[PopsiclesData]:
        """Gets the menu of this StoreSchema.


        :return: The menu of this StoreSchema.
        :rtype: List[PopsiclesData]
        """
        return self._menu

    @menu.setter
    def menu(self, menu: List[PopsiclesData]):
        """Sets the menu of this StoreSchema.


        :param menu: The menu of this StoreSchema.
        :type menu: List[PopsiclesData]
        """

        self._menu = menu
