# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from als_popsicles_igloo import als_popsicles_igloo_pb2 as als__popsicles__igloo_dot_als__popsicles__igloo__pb2


class MenuRequestStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.requestMenu = channel.unary_unary(
        '/protos.als_popsicles_igloo.MenuRequest/requestMenu',
        request_serializer=als__popsicles__igloo_dot_als__popsicles__igloo__pb2.Menu.SerializeToString,
        response_deserializer=als__popsicles__igloo_dot_als__popsicles__igloo__pb2.Menu.FromString,
        )


class MenuRequestServicer(object):
  """The greeting service definition.
  """

  def requestMenu(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MenuRequestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'requestMenu': grpc.unary_unary_rpc_method_handler(
          servicer.requestMenu,
          request_deserializer=als__popsicles__igloo_dot_als__popsicles__igloo__pb2.Menu.FromString,
          response_serializer=als__popsicles__igloo_dot_als__popsicles__igloo__pb2.Menu.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.als_popsicles_igloo.MenuRequest', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
